# netlify.toml

[build]
  publish = "."      # serve index.html and any static assets from repo root

# Map the Edge Function "data" to the path /data
[[edge_functions]]
  path = "/data"
  function = "data"
